### PR TITLE
Proposal: Compatibility with browserify

### PR DESCRIPTION
**Pull request by pagenoare**
Hey,

I'm using [browserify](http://browserify.org/), and would like to use your plugin with it. I've managed to do it with this patches. I haven't done the minification though, I don't know which tool you've been using for that.

Thanks for the plugin!

Regards,
Kacper.

### CODE REVIEW

**Comment by pagenoare** [comment]
BTW, I took an idea from Leaflet/Leaflet#1572 about changing `this` to `window`.

Also, I've created simple example: https://github.com/pagenoare/browserify-bootstrap-example/commit/dda6192fa31ad6c134a913d65cca96ba82cc9aa2

Regards,
Kacper.

**Comment by CWSpear** [comment]
I should make a note about minification. Sorry. 

So you'll need me to publish this to `npm`, right? I've never actually used `browserify`, but that's how it works, correct?

**Comment by pagenoare** [comment]
Yeah publishing it to npm registry would be slightly cleaner, because then I could change this line: https://github.com/pagenoare/browserify-bootstrap-example/commit/dda6192fa31ad6c134a913d65cca96ba82cc9aa2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R15

to look like:

```js
    "bootstrap-hover-dropdown": ""
```

Without putting this into [registry](https://www.npmjs.com/) (but merging this PR, package.json must be inside repo) this plugin could be also accessed like:

```js
    "bootstrap-hover-dropdown": "CWSpear/bootstrap-hover-dropdown"
```

Thanks.

**Comment by CWSpear** [comment]
I have published to `npm` before. But right now, it seems to be down or something? I keep getting `publish Failed PUT 500` errors trying to publish. I updated `npm`, but I wonder if it's related to the `node` `0.12.0` release.

**Comment by CWSpear** [comment]
Ah, I figured it out. My login was stale... strange that that resulted in a 500 error (see https://github.com/npm/npm/issues/6669)

Anyway, `npm install bootstrap-hover-dropdown` away!

**Comment by pagenoare** [comment]
Thanks @CWSpear!

**Pull request merged**
