### PR TITLE
Don't do anything when the navbar is collapsed.

### LINKED ISSUE #136: Don't do anything when navbar is collapsed
I find it very hard to use a collapsed navbar with this plugin. I think it's better to not do anything when the navbar is collapsed. I added a simple test for if the navbar is collapsed in https://github.com/jfly/bootstrap-hover-dropdown/commit/f426275df84c415435f2c22e2af3da0367bb0052. I am happy to submit a PR if interested!

### PR DESCRIPTION
**Pull request by jfly**
This fixes #136.

### CODE REVIEW

**Comment by CWSpear** [comment]
There is actually one thing I hadn't considered: What if there is a `.navbar-toggle` somewhere else visible on the page for any reason. This would break the functionality for all dropdowns unintentionally.

This is an issue that we _have_ tried solving before: https://github.com/CWSpear/bootstrap-hover-dropdown/commit/6aba7e194eaaebd29a1e21fa5a78b529496ca446 & https://github.com/CWSpear/bootstrap-hover-dropdown/issues/11, and I think there are others, but can't find them right off.

**Comment by jfly** [comment]
I see. It looks like the `shouldHover` method was removed in 0962a027d536cab956860ae92acc180c8c6c25ac.

I was stuck thinking that this plugin is only used for navbars. I did not realize that this is meant to be used for dropdowns *anywhere* on a page. I've changed the condition to only fire for dropdowns that are inside a navbar that is collapsed.

**Comment by CWSpear** [comment]
Alright, I think that's better! Not at my computer, but I'll try and get this merged and a new version out sometime today.

**Comment by jfly** [comment]
Bump. Any news here?

**Comment by CWSpear** [comment]
Thanksgiving holiday and all that jazz. Sorry about that. Thanks for the ping to remind me =)

Anyway, merged. I did a minor version bump since it *could* break some extreme edge cases. (Then did another patch bump cuz I messed up the first one). `v2.2.1` is tagged and published. Thanks!

**Comment by jfly** [comment]
Sweet, thanks!

**Pull request merged**
